name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Frontend
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('**/yarn.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install wasm-pack
        run: cargo install --debug wasm-pack
        continue-on-error: true
      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
      - name: Generate WebAssembly
        run: wasm-pack build bindings

      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: frontend
      - name: Link Frontend to Generated Bindings
        run: |
          pushd bindings/pkg
          yarn link
          popd
          pushd frontend
          yarn link laskea-bindings
      - name: Type-check Frontend
        run: yarn build:check
        working-directory: frontend
      - name: Build Frontend
        run: yarn build
        working-directory: frontend

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: frontend/dist
        if: github.ref == 'refs/heads/master'
